name: learn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - attrs=19.3.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.8.2
  - blas=1.0
  - bleach=3.1.5
  - branca=0.4.1
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - chardet=3.0.4
  - cryptography=3.0
  - cycler=0.10.0
  - cython=0.29.13
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - folium=0.11.0
  - freetype=2.10.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - joblib=0.16.0
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libxgboost=0.90
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - nltk=3.4.5
  - notebook=6.1.2
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=0.25.3
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.1
  - plotly=4.1.1
  - prometheus_client=0.8.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - py-xgboost=0.90
  - py4j=0.10.7
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pyspark=2.4.4
  - python=3.6.9
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pyzmq=18.1.1
  - readline=7.0
  - requests=2.24.0
  - retrying=1.3.3
  - scikit-learn=0.21.3
  - scipy=1.5.0
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=49.2.1
  - simplegeneric=0.8.1
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.32.3
  - statsmodels=0.11.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.36.1
  - traitlets=4.3.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
