name: learn-env
channels:
  - defaults
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.0
  - blas=1.0=mkl
  - boto=2.49.0
  - boto3=1.9.234
  - botocore=1.12.234
  - bz2file=0.98
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cloog=0.18.0=10
  - cryptography=2.7
  - cryptography-vectors=2.7
  - cycler=0.10.0
  - cython=0.29.13
  - decorator=4.4.0
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gensim=3.7.3
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=5.1.2=6
  - graphite2=1.3.13
  - graphviz=2.40.1
  - h5py=2.9.0
  - harfbuzz=1.8.8
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - intel-openmp
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - isl=0.12.2=1
  - jedi=0.15.1
  - jinja2=2.10.1
  - jmespath=0.9.4
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.2 
  - jupyter_client=5.3.3
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.5.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.0.10
  - libxgboost=0.90
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvm-openmp=4.0.1
  - lxml=4.4.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4=233
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mpc=1.0.3
  - mpfr=3.1.5
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nltk=3.4.5
  - notebook=5.7.8
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1d
  - pandas=1.0.3
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - pixman=0.38.0
  - plotly=4.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py-xgboost=0.90
  - py4j=0.10.7
  - pycparser=2.19
  - pydotplus=2.0.2
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyrsistent=0.14.11
  - pysocks=1.7.1
  - pyspark=2.4.4
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyyaml
  - pyzmq=18.1.0
  - readline=7.0
  - requests=2.22.0
  - retrying=1.3.3
  - s3transfer=0.2.1
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.2.0
  - simplegeneric=0.8.1
  - six=1.12.0
  - smart_open=1.8.4
  - soupsieve=1.9.2
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.2
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - atomicwrites==1.3.0
    - bleach==1.5.0
    - branca==0.3.1
    - convertdate==2.1.3
    - dill==0.3.0
    - ecos==2.0.7.post1
    - ephem==3.7.7.0
    - folium==0.9.1
    - future==0.17.1
    - gast==0.2.2
    - grpcio==1.21.1
    - holidays==0.9.11
    - html5lib==0.9999999
    - imbalanced-learn==0.4.3
    - importlib-metadata==0.17
    - ipynb==0.5.1
    - keras==2.2.4
    - keras-applications==1.0.4
    - keras-preprocessing==1.0.2
    - lunardate==0.2.0
    - markdown==3.1.1
    - more-itertools==7.0.0
    - multiprocess==0.70.8
    - obscure==1.0.1
    - osqp==0.6.1
    - pandasql==0.7.3
    - pillow==6.1.0
    - pluggy==0.12.0
    - protobuf==3.8.0
    - py==1.8.0
    - pystan==2.17.1.0
    - pytest==3.7.0
    - graphviz==0.11
    - setuptools-git==1.2
    - sqlalchemy==1.3.8
    - tensorboard==1.6.0
    - tensorflow==1.6.0
    - termcolor==1.1.0
    - werkzeug==0.15.4
    - zipp==0.5.1
prefix: /anaconda3/envs/learn-test-env
